# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lookout/core/api/service_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bblfsh.github.com.gogo.protobuf.gogoproto import gogo_pb2 as github_dot_com_dot_gogo_dot_protobuf_dot_gogoproto_dot_gogo__pb2
import importlib
gopkg_dot_in_dot_bblfsh_dot_sdk_dot_v1_dot_uast_dot_generated__pb2 = importlib.import_module('bblfsh.gopkg.in.bblfsh.sdk.v1.uast.generated_pb2')
from lookout.core.api import event_pb2 as lookout_dot_core_dot_api_dot_event__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lookout/core/api/service_data.proto',
  package='pb',
  syntax='proto3',
  serialized_pb=_b('\n#lookout/core/api/service_data.proto\x12\x02pb\x1a-github.com/gogo/protobuf/gogoproto/gogo.proto\x1a+gopkg.in/bblfsh/sdk.v1/uast/generated.proto\x1a\x1clookout/core/api/event.proto\"\x98\x01\n\x04\x46ile\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\r\x12\x0c\n\x04hash\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\x0c\x12\x39\n\x04uast\x18\x05 \x01(\x0b\x32!.gopkg.in.bblfsh.sdk.v1.uast.NodeB\x08\xe2\xde\x1f\x04UAST\x12\x10\n\x08language\x18\x06 \x01(\t:\x08\xa0\xa1\x1f\x00\xe0\xa1\x1f\x01\"B\n\x06\x43hange\x12\x16\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x08.pb.File\x12\x16\n\x04head\x18\x02 \x01(\x0b\x32\x08.pb.File:\x08\xa0\xa1\x1f\x00\xe0\xa1\x1f\x01\"\xf3\x01\n\x0e\x43hangesRequest\x12\"\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x14.pb.ReferencePointer\x12\"\n\x04head\x18\x02 \x01(\x0b\x32\x14.pb.ReferencePointer\x12\x17\n\x0finclude_pattern\x18\x03 \x01(\t\x12\x17\n\x0f\x65xclude_pattern\x18\x04 \x01(\t\x12\x18\n\x10\x65xclude_vendored\x18\x05 \x01(\x08\x12\x15\n\rwant_contents\x18\x06 \x01(\x08\x12\x1f\n\twant_uast\x18\x07 \x01(\x08\x42\x0c\xe2\xde\x1f\x08WantUAST\x12\x15\n\rwant_language\x18\x08 \x01(\x08\"\xd1\x01\n\x0c\x46ilesRequest\x12&\n\x08revision\x18\x01 \x01(\x0b\x32\x14.pb.ReferencePointer\x12\x17\n\x0finclude_pattern\x18\x02 \x01(\t\x12\x17\n\x0f\x65xclude_pattern\x18\x03 \x01(\t\x12\x18\n\x10\x65xclude_vendored\x18\x04 \x01(\x08\x12\x15\n\rwant_contents\x18\x05 \x01(\x08\x12\x1f\n\twant_uast\x18\x06 \x01(\x08\x42\x0c\xe2\xde\x1f\x08WantUAST\x12\x15\n\rwant_language\x18\x07 \x01(\x08\x32`\n\x04\x44\x61ta\x12.\n\nGetChanges\x12\x12.pb.ChangesRequest\x1a\n.pb.Change0\x01\x12(\n\x08GetFiles\x12\x10.pb.FilesRequest\x1a\x08.pb.File0\x01\x42\x04\xc8\xe1\x1e\x00\x62\x06proto3')
  ,
  dependencies=[github_dot_com_dot_gogo_dot_protobuf_dot_gogoproto_dot_gogo__pb2.DESCRIPTOR,gopkg_dot_in_dot_bblfsh_dot_sdk_dot_v1_dot_uast_dot_generated__pb2.DESCRIPTOR,lookout_dot_core_dot_api_dot_event__pb2.DESCRIPTOR,])




_FILE = _descriptor.Descriptor(
  name='File',
  full_name='pb.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='pb.File.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='pb.File.mode', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='pb.File.hash', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='pb.File.content', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uast', full_name='pb.File.uast', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\336\037\004UAST')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='pb.File.language', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\240\241\037\000\340\241\037\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=318,
)


_CHANGE = _descriptor.Descriptor(
  name='Change',
  full_name='pb.Change',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='pb.Change.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='head', full_name='pb.Change.head', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\240\241\037\000\340\241\037\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=386,
)


_CHANGESREQUEST = _descriptor.Descriptor(
  name='ChangesRequest',
  full_name='pb.ChangesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='pb.ChangesRequest.base', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='head', full_name='pb.ChangesRequest.head', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='include_pattern', full_name='pb.ChangesRequest.include_pattern', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exclude_pattern', full_name='pb.ChangesRequest.exclude_pattern', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exclude_vendored', full_name='pb.ChangesRequest.exclude_vendored', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='want_contents', full_name='pb.ChangesRequest.want_contents', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='want_uast', full_name='pb.ChangesRequest.want_uast', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\336\037\010WantUAST')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='want_language', full_name='pb.ChangesRequest.want_language', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=632,
)


_FILESREQUEST = _descriptor.Descriptor(
  name='FilesRequest',
  full_name='pb.FilesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='revision', full_name='pb.FilesRequest.revision', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='include_pattern', full_name='pb.FilesRequest.include_pattern', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exclude_pattern', full_name='pb.FilesRequest.exclude_pattern', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exclude_vendored', full_name='pb.FilesRequest.exclude_vendored', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='want_contents', full_name='pb.FilesRequest.want_contents', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='want_uast', full_name='pb.FilesRequest.want_uast', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\336\037\010WantUAST')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='want_language', full_name='pb.FilesRequest.want_language', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=635,
  serialized_end=844,
)

_FILE.fields_by_name['uast'].message_type = gopkg_dot_in_dot_bblfsh_dot_sdk_dot_v1_dot_uast_dot_generated__pb2._NODE
_CHANGE.fields_by_name['base'].message_type = _FILE
_CHANGE.fields_by_name['head'].message_type = _FILE
_CHANGESREQUEST.fields_by_name['base'].message_type = lookout_dot_core_dot_api_dot_event__pb2._REFERENCEPOINTER
_CHANGESREQUEST.fields_by_name['head'].message_type = lookout_dot_core_dot_api_dot_event__pb2._REFERENCEPOINTER
_FILESREQUEST.fields_by_name['revision'].message_type = lookout_dot_core_dot_api_dot_event__pb2._REFERENCEPOINTER
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['Change'] = _CHANGE
DESCRIPTOR.message_types_by_name['ChangesRequest'] = _CHANGESREQUEST
DESCRIPTOR.message_types_by_name['FilesRequest'] = _FILESREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), dict(
  DESCRIPTOR = _FILE,
  __module__ = 'lookout.core.api.service_data_pb2'
  # @@protoc_insertion_point(class_scope:pb.File)
  ))
_sym_db.RegisterMessage(File)

Change = _reflection.GeneratedProtocolMessageType('Change', (_message.Message,), dict(
  DESCRIPTOR = _CHANGE,
  __module__ = 'lookout.core.api.service_data_pb2'
  # @@protoc_insertion_point(class_scope:pb.Change)
  ))
_sym_db.RegisterMessage(Change)

ChangesRequest = _reflection.GeneratedProtocolMessageType('ChangesRequest', (_message.Message,), dict(
  DESCRIPTOR = _CHANGESREQUEST,
  __module__ = 'lookout.core.api.service_data_pb2'
  # @@protoc_insertion_point(class_scope:pb.ChangesRequest)
  ))
_sym_db.RegisterMessage(ChangesRequest)

FilesRequest = _reflection.GeneratedProtocolMessageType('FilesRequest', (_message.Message,), dict(
  DESCRIPTOR = _FILESREQUEST,
  __module__ = 'lookout.core.api.service_data_pb2'
  # @@protoc_insertion_point(class_scope:pb.FilesRequest)
  ))
_sym_db.RegisterMessage(FilesRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\310\341\036\000'))
_FILE.fields_by_name['uast'].has_options = True
_FILE.fields_by_name['uast']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\336\037\004UAST'))
_FILE.has_options = True
_FILE._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\240\241\037\000\340\241\037\001'))
_CHANGE.has_options = True
_CHANGE._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\240\241\037\000\340\241\037\001'))
_CHANGESREQUEST.fields_by_name['want_uast'].has_options = True
_CHANGESREQUEST.fields_by_name['want_uast']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\336\037\010WantUAST'))
_FILESREQUEST.fields_by_name['want_uast'].has_options = True
_FILESREQUEST.fields_by_name['want_uast']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\342\336\037\010WantUAST'))

_DATA = _descriptor.ServiceDescriptor(
  name='Data',
  full_name='pb.Data',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=846,
  serialized_end=942,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetChanges',
    full_name='pb.Data.GetChanges',
    index=0,
    containing_service=None,
    input_type=_CHANGESREQUEST,
    output_type=_CHANGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetFiles',
    full_name='pb.Data.GetFiles',
    index=1,
    containing_service=None,
    input_type=_FILESREQUEST,
    output_type=_FILE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATA)

DESCRIPTOR.services_by_name['Data'] = _DATA

# @@protoc_insertion_point(module_scope)
